vim.keymap.set({ 'n' }, 'n', 'nzz')
vim.keymap.set({ 'n' }, 'N', 'Nzz')
vim.keymap.set({ 'n' }, '<Esc>', function()
    vim.cmd 'nohlsearch'
    return '<Esc>'
end, { remap = true })
vim.keymap.set({ 'n' }, 'H', '<cmd>bn<cr>')
vim.keymap.set({ 'n' }, 'L', '<cmd>bp<cr>')
vim.keymap.set({ 'n' }, 'U', function()

end)
vim.keymap.set({ 'n' }, '<C-j>', function()
    

end)
vim.keymap.set({ 'n' }, '<C-k>', function()

end)
vim.keymap.set({ 'n' }, 'j', 'gj')
vim.keymap.set({ 'n' }, 'k', 'gk')
vim.keymap.set({ 'n' }, '<C-i>', '<C-i>')
vim.keymap.set({ 'n' }, '<Tab>', 'gt')
vim.keymap.set({ 'n' }, '<S-Tab>', 'gT')
vim.keymap.set({ 'n' }, '<C-Tab>', '<cmd>tabnew<cr>')
vim.keymap.set({ 'n' }, '<C-S-Tab>', '<cmd>tabclose<cr>')
vim.keymap.set({ 'n' }, '<A-j>', '<C-w>j')
vim.keymap.set({ 'n' }, '<A-k>', '<C-w>k')
vim.keymap.set({ 'n' }, '<A-l>', '<C-w>l')
vim.keymap.set({ 'n' }, '<A-h>', '<C-w>h')
vim.keymap.set({ 'n' }, '<A-J>', '<C-w>J')
vim.keymap.set({ 'n' }, '<A-K>', '<C-w>K')
vim.keymap.set({ 'n' }, '<A-L>', '<C-w>L')
vim.keymap.set({ 'n' }, '<A-H>', '<C-w>H')
vim.keymap.set({ 'n' }, '<A-o>', '<C-w>o')
vim.keymap.set({ 'n' }, '<A-c>', '<C-w>c')
vim.keymap.set({ 'n' }, '<A-s>', '<C-w>s')
vim.keymap.set({ 'n' }, '<A-v>', '<C-w>v')
vim.keymap.set({ 'n' }, '<A-t>', '<C-w>T')
vim.keymap.set({ 'n' }, '<A-,>', '<C-w><')
vim.keymap.set({ 'n' }, '<A-.>', '<C-w>>')
vim.keymap.set({ 'n' }, '<A-->', '<C-w>-')
vim.keymap.set({ 'n' }, '<A-=>', '<C-w>+')
vim.keymap.set({ 'n' }, '<A-;>', '<C-w>=')
